services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/processed/chroma_db:/chroma/chroma